/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'medlclouddev' at '1/3/18 11:02 AM' with Gradle 2.14.1
 *
 * @author medlclouddev, @date 1/3/18 11:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
